# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build and deploy

on:
  workflow_dispatch:
    

jobs:
  build:
    name: Build and upload artifacts
    uses: ./.github/workflows/build.yml
  
  deploy_dev:
    needs: build
    environment: dev
    name: Deploy dev
    uses: ./.github/workflows/az-deploy.yml
    with:
      ENVIRONMENT: dev
      RESOURCE_GROUP: LC.API.Dev
      APP_SERVICE_PLAN: LCWinSP
      APP_SERVICE_PLAN_RESOURCE_GROUP: LC.AppServicePlans
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      SQL_ADMIN_GROUP: ${{ secrets.SQL_ADMIN_GROUP }}
      SQL_ADMIN_GROUP_SID: ${{ secrets.SQL_ADMIN_GROUP_SID }}

  deploy_staging:
    needs: deploy_dev
    environment: staging
    name: Deploy staging
    uses: ./.github/workflows/az-deploy.yml
    with:
      ENVIRONMENT: staging
      RESOURCE_GROUP: LC.API.Staging
      APP_SERVICE_PLAN: LCWinSP
      APP_SERVICE_PLAN_RESOURCE_GROUP: LC.AppServicePlans
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      SQL_ADMIN_GROUP: ${{ secrets.SQL_ADMIN_GROUP }}
      SQL_ADMIN_GROUP_SID: ${{ secrets.SQL_ADMIN_GROUP_SID }}

  deploy_prod:
    needs: deploy_staging
    environment: prod
    name: Deploy prod
    uses: ./.github/workflows/az-deploy.yml
    with:
      ENVIRONMENT: prod
      RESOURCE_GROUP: LC.API.Production
      APP_SERVICE_PLAN: LCWinSP
      APP_SERVICE_PLAN_RESOURCE_GROUP: LC.AppServicePlans
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      SQL_ADMIN_GROUP: ${{ secrets.SQL_ADMIN_GROUP }}
      SQL_ADMIN_GROUP_SID: ${{ secrets.SQL_ADMIN_GROUP_SID }}